---
title: "CitMotion"
author: "Lisa Tang"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(usethis)
use_git_config(user.name= "lisat3298", user.email="lisa.t3298@gmail.com")
```

```{r libraries}
library(tidyverse)
library(ggplot2)
```


```{r load-data, message = FALSE}
citymotion <- read.csv("~/R/CityMotion/Duration - Duration Data.csv")
```

```{r}
ggplot(data = citymotion, 
       mapping = aes(x = predicted_duration, y = actual_duration)) + 
   geom_point() + 
   labs(title = "Sentiance Predicted Duration of Travel vs Actual Duration of Travel",
        x = "Predicted Duration (Minutes)", y = "Actual Duration (Minutes)")
```

```{r}
citymotion %>% 
  mutate(diff = actual_duration - predicted_duration) %>% 
  ggplot(citymotion, mapping = aes(x = actual_duration, y = diff, color = mode)) +
   geom_point() + 
   labs(title = "Difference in Sentiance Predicted Duration for Different Travel Times", color = "Mode of Transport",
        x = "Actual Travel Duration (min)", y = "Difference in Duration (actual - predicted, min)")
```
```{r}
citymotion %>% 
  mutate(diff = actual_duration - predicted_duration) %>% 
  ggplot(citymotion, mapping = aes(x = actual_duration, y = diff, color = mode)) +
  ylim(-20, 20) + xlim(0,20) +
   geom_point() + 
   labs(title = "Difference in Sentiance Predicted Duration for Different Travel Times", color = "Mode of Transport",
        x = "Actual Travel Duration (min)", y = "Difference in Duration (actual - predicted, min)")
```
```{r load-data, message = FALSE}
distance <- read.csv("~/R/CityMotion/Distance.csv")
```

```{r}
distance %>% 
  mutate(diff = actual_distance - predicted_distance) %>% 
  ggplot(distance, mapping = aes(x = actual_distance, y = diff, color = mode)) +
   geom_point() + 
   labs(title = "Difference in Sentiance Predicted Distances", color = "Mode of Transport",
        x = "Actual Travel Distance (km)", y = "Difference in Distance (actual - predicted, km)")
```



```{r}
distance %>% 
  mutate(diff = actual_distance - predicted_distance) %>% 
  ggplot(distance, mapping = aes(x = actual_distance, y = diff, color = mode)) +
  ylim(-20, 20) + xlim(0,20) +
   geom_point() + 
  geom_jitter() +
   labs(title = "Difference in Sentiance Predicted Distances", color = "Mode of Transport",
        x = "Actual Travel Distance (km)", y = "Difference in Distance (actual - predicted, km)")
```
